/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package porcodio;
import com.google.maps.errors.ApiException;

import java.io.IOException;

public class UseMaps {
    public static void main(String[] args) throws ApiException, InterruptedException, IOException {
        new Gui();   
    }
}
